config/routes.rb
Checkist::Application.routes.draw do
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users,    :only => [:new, :create]
  resources :todos,    :only => [:index, :create]
  
  root :to => 'todos#index'
  
  match "/about",   :to => "pages#about"
  match "/help",    :to => "pages#help"
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup',  :to => 'users#new'
  
  match '/mark_complete/:id' => 'todos#mark_complete'
  match '/show_assign/:id'   => 'todos#show_assign'
  match '/todos/destroy/:id' => 'todos#destroy'
  match '/assign/:id'        => 'todos#assign'
  match '/accept/:id'        => 'todos#accept'
  match '/reject/:id'        => 'todos#reject'
  

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :content, :due_date, :complete
  
  validates :content, :presence => true
  
  belongs_to :creator, :foreign_key => 'creator', :class_name => 'User'
  
  belongs_to :owner,         :foreign_key => 'owner',         :class_name => 'User', :inverse_of => :assigned_todos
  belongs_to :pending_owner, :foreign_key => 'pending_owner', :class_name => 'User', :inverse_of => :incoming_todos
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  
  email_regexp = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
                   :length => { :maximum => 50}
  
  validates :email, :presence => true,
                    :format   => { :with => email_regexp },
                    :uniqueness => { :case_sensitive => false }
  
  validates :password, :presence => true,
                       :confirmation => true,
                       :format   => { :with => /(?:\d\D)|(?:\D\d)/ },
                       :length   => { :minimum => 5 }
  
  before_save :encrypt_password
  
  has_many :assigned_todos, :foreign_key => 'owner',         :class_name => 'Todo', :inverse_of => :owner
  has_many :incoming_todos, :foreign_key => 'pending_owner', :class_name => 'Todo', :inverse_of => :pending_owner
  
  def has_password?(submitted_password)
    password == encrypt(submitted_password)
  end
  
  private
  
  def encrypt_password
    self.password = encrypt(password)
  end
  
  def encrypt(string)
    Digest::MD5.hexdigest(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  helper :all
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @page_title = "Home"
  end

  def about
    @page_title = "About"
  end

  def help
    @page_title = "Help"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @page_title = "Sign in"
  end
  
  def create
    user = User.find_by_email(params[:session][:email])
    if user.nil?
      flash.now[:error] = "Invalid eMail"
      
      @page_title = "Sign in"
      render 'new'
    elsif !user.has_password?(params[:session][:password])
      flash.now[:error] = "Invalid password"
      
      @page_title = 'Sign in'
      render 'new'
    else
      sign_in user
      redirect_to root_path
    end
  end
  
  def destroy
     sign_out
     redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    if signed_in?
      @page_title = "Home"
      
      @assigned_todos = current_user.assigned_todos.where(:complete => false, :pending_owner => nil)
      @incoming_todos = current_user.incoming_todos
      
      @todo_item = Todo.new
    else
      render 'pages/home'
    end
  end
  
  def accept
    todo_item = current_user.incoming_todos.where(:id => params[:id]).first
    
    if !todo_item.nil?
      todo_item.owner = current_user
      todo_item.pending_owner = nil;
      todo_item.save
    end
    
    redirect_to root_path
  end
  
  def reject
    todo_item = current_user.incoming_todos.where(:id => params[:id]).first
    
    if !todo_item.nil?
      todo_item.pending_owner = nil;
      todo_item.save
    end
    
    redirect_to root_path
  end
  
  def mark_complete
    todo_item = current_user.assigned_todos.where(:id => params[:id]).first
    
    if !todo_item.nil?
      todo_item.complete = true;
      todo_item.save
    end
    
    redirect_to root_path
  end
  
  def create
    @todo_item = Todo.new(params[:todo])
    @todo_item.owner   = current_user
    @todo_item.creator = current_user
    
    if @todo_item.save
      @assigned_todos = current_user.assigned_todos
      @todo_item = Todo.new
      redirect_to root_path
    else
      @assigned_todos = current_user.assigned_todos
      render 'list'
    end
  end
  
  def destroy
    todo_item = current_user.assigned_todos.where(:id => params[:id]).first
    
    if !todo_item.nil?
      todo_item.destroy
    end
    
    redirect_to root_path
  end
  
  def assign
    todo_item = current_user.assigned_todos.where(:id => params[:id]).first
    
    new_user = User.find_by_email(params[:assign_todo][:email])
    
    if !todo_item.nil? and !new_user.nil?
      todo_item.pending_owner = new_user
      todo_item.save
    end
    
    redirect_to root_path
  end
  
  def show_assign
    @todo_item = current_user.assigned_todos.where(:id => params[:id]).first
    
    if @todo_item.nil?
      redirect_to root_path
    end
    
    @page_title = "Home"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :not_logged_in
  
  def new
    @page_title = "Sign Up"
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    
    if @user.save
      sign_in @user
      redirect_to root_path
    else
      @page_title = "Sign Up"
      render "new"
    end
  end
  
  private
    def not_logged_in
      redirect_to root_path and return if signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:auth_token] = user.email
    current_user = user
  end
  
  def sign_out
    cookies.delete(:auth_token)
    current_user= nil
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def current_user
    @current_user ||= user_from_auth_token
  end
  
  def signed_in?
    !(current_user.nil?)
  end
  
  def authenticate
     deny_access unless signed_in?
  end
  
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page"
  end

  private
    def user_from_auth_token
      userEmail = remember_token
      User.find_by_email(userEmail)
    end
    
    def remember_token
      cookies[:auth_token] || nil
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>Maybe the 'l' stood for "long"?</footer>

app/views/layouts/_header.html.erb
<header>
    <% if signed_in? %>
        <h1>Welcome <%= current_user.name %></h1>
    <% else %>
        <h1>Welcome to Checkist</h1>
    <% end %>
    <nav>
        <%= link_to "Home", root_path %> |
        <%= link_to "About", about_path %> | 
        <%= link_to "Help", help_path %>
    </nav>
    
    <% if signed_in? %>
        <%= link_to "Log Out", signout_path, {'class' => 'authLink'} %>
    <% else %>
        <%= link_to "Log In", signin_path, {'class' => 'authLink'} %>
        <%= link_to "Sign Up", signup_path, {'class' => 'signupLink'} %>
    <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Checkist | <%= @page_title %></title>
  <meta name="description" content="Simple checklist manager for people who like people but hate clutter">
  <meta name="author" content="Ben Batschelet">

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= stylesheet_link_tag "base",   :media => 'screen' %>
  <%= stylesheet_link_tag "screen", :media => 'screen' %>
  
  <%= javascript_include_tag "jquery-1.6.2.min" %>
  
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <%= render 'layouts/header' %>
  
  <div id="content">
    <%= yield %>
  </div>
  
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h2>We Take the 'l' of Checklists!</h2>
<p>...and no, we don't know what that means exactly, but it sounds good doesn't it?</p>
<p><%= link_to "Log in", signin_path, {'class' => 'authLink'} %> if you're an existing user or please <%= link_to "sign up", signup_path, {'class' => 'signupLink'} %> if you're new, and you can start making checkists in a matter of minutes!</p>

app/views/todos/index.html.erb
<% if @incoming_todos.count > 0 %>
  <div id="incoming_todos">
    <h2>Incoming Todos</h2>
    
    <ul class="todo_list">
      <% for pending_item in @incoming_todos %>
        <li>
          <%= pending_item.content %>
          
          <div class="assigned_from">
            From <%= pending_item.owner.name %>
          </div>
          
          <% if !pending_item.due_date.nil? %>
            <div class="pending_due_date">
              Due on <%= pending_item.due_date %>
            </div>
          <% end -%>
          
          <div class="control_incoming_item">
            <%= link_to "Accept", { :controller => "todos", :action => "accept", :id => pending_item.id } %> |
            <%= link_to "Reject", { :controller => "todos", :action => "reject", :id => pending_item.id } %>
          </div>
        </li>
      <% end -%>
    </ul>
  </div>
<% end -%>

<div id="existing_todos">
  <h2>Your Todos</h2>
  
  <ul class="todo_list">
    <% for todo_item in @assigned_todos %>
      <li>
        <%= link_to raw("&#10004;"), { :controller => "todos", :action => "mark_complete", :id => todo_item.id }, { :title => "Mark Complete", :class => 'check_item' } %>
        <%= todo_item.content %>
        <% if !todo_item.due_date.nil? %>
          <div class="due_date">
            Due on <%= todo_item.due_date %>
          </div>
        <% end -%>
        
        <%= link_to raw("&#10150;"), { :controller => "todos", :action => "show_assign", :id => todo_item.id }, { :title => "Assign to...", :class => 'reassign_item' } %>
        <%= link_to raw("&#10008;"), { :controller => "todos", :action => "destroy", :id => todo_item.id }, { :title => "Delete...", :class => 'delete_item' } %>
      </li>
    <% end -%>
      <li>
        <%= form_for @todo_item do |f| -%>
          <%= f.label :content, "New" %>
          <%= f.text_field :content, :size => 64 %>
          
          <%= f.label :due_date, "Due" %>
          <%= f.text_field :due_date, :size => 8 %>
          
          <%= f.submit "Add" %>
        <% end -%>
      </li>
  </ul>
</div>

app/views/todos/show_assign.html.erb
<div id="existing_todos">
  <ul class="todo_list">
    <li>
      <%= @todo_item.content %>
      <% if !@todo_item.due_date.nil? %>
        <div class="due_date">
          Due on <%= @todo_item.due_date %>
        </div>
      <% end -%>
    </li>
    <li>
      <%= form_for :assign_todo, :url => { :controller => "todos", :action => "assign", :id => @todo_item.id }, :html => { :id => 'assign_form' } do |f| -%>
        <%= f.label :email, "User (eMail)" %>
        <%= f.email_field :email, :size => 64 %>
        
        <%= f.submit "Assign" %>
      <% end -%>
    </li>
  </ul>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| -%>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :email, "eMail" %>
    <%= f.email_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :password, "Password" %>
    <%= f.password_field :password %>
  </div>
  
  <div class="field">
    <%= f.label :password_confirm, "Confirmation" %>
    <%= f.password_field :password_confirm %>
  </div>
  
  <div class="actions">
    <%= f.submit "Sign Me Up!", :disable_with => 'Doing it...' %>
  </div>
<% end -%>